### ISSUE TITLE
Clarification for unofficial client usage

### ISSUE THREAD

**Issue by ryanhlewis** [local-first-web/relay#7]
Your Github repo has recently caught my eye, and I've been looking to dabble with it.

However, I am working with C# and Unity, not exactly Javascript. Therefore, I am not using your built Client and instead opting for simple WebSocket connections. This has all been fine and dandy, and I've managed to connect clients to their websockets, but not to one another.

Therein, my questions lie. I went through your source code a number of times to figure this out, but as a last resort, I am requesting clarification from you. Here are my questions:

1. How does the DocumentID get sent in the Introduction Request?

It is clear that the Server seems to take the Introduction Request and uses it to find information such as username and documentId. The username part is immediately visible: /introduction/username. However, the DocumentID is not. I have tried attaching it as a header to the request, under the name "Join", but that did not seem to work. I have tried attaching it as a parameter in the URL, as /introduction/username?join=document, but that failed too. I even created a KeyValue JSON message with the key "Join" to send, and still, nothing.

2. How does the Connection Endpoint function?

You say the Client and Server do not communicate with one another on the connection endpoint. How exactly does this function? Is the client given some public IP of another client and some open port? 

3. Is there support for multiple people?

I am not talking large-scale support, 20+, etc. but rather for even small groups. If the server is a relay server, how large can it expand? It seems that you iterate "two" over and over again within the documentation, but within your code you explicitly call and allow for multiple DocumentIds, which seems to suggest there is support for multiple clients connected to one another, in a rather strange fashion. 

Thanks, and I wish you all the well in this endeavor.

**Comment by HerbCaudill** [comment]
Thanks, Ryan. That's an interesting use case. I think if I were doing this, I would take the `Client` class and and tests, and basically translate everything directly from TypeScript to C#. Then once the tests were passing, you could refactor it to make it more idiomatic in C#. 

> How does the DocumentID get sent in the Introduction Request?

> How does the Connection Endpoint function?

Here's how two peers connect: 

1. Alice makes a websocket connection to the server on `/introduction/alice`.
2. On that connection, Alice sends a `Join` message indicating she's interested in document `abc`.

    ```js
    { type: 'Join', documentIds: ['abc'] }
    ```

3. Bob makes a websocket connection to the server on `/introduction/bob`.
4. Bob also sends a `Join` message indicating he's interested in document `abc`.

    ```js
    { type: 'Join', documentIds: ['abc'] }
    ```

5. On receiving Bob's message, the server sees that Bob and Alice are interested in the same document. So the server sends Alice an introduction to Bob: 

    ```js
    { type: 'Introduction', userName: 'bob', documentIds: ['abc'] }
    ```

    The server also sends Bob an introduction to Alice: 

    ```js
    { type: 'Introduction', userName: 'alice', documentIds: ['abc'] }
    ```

6. Alice makes a new websocket connection to the server on `/connection/alice/bob/abc`. (The server doesn't do anything yet, because Bob hasn't connected.) 
7. Bob makes a new websocket connection to the server on `/connection/bob/alice/abc`. 
8. Now that the server has mutual connection requests from Bob and Alice, it pipes together the websockets created in steps 6 and 7: So every message Alice sends to the server on this socket is passed on to Bob, and every message Bob sends is passed on to Alice. 

> You say the Client and Server do not communicate with one another on the connection endpoint

Alice's messages to Bob are sent to the server, and from the server to Bob; and vice versa. On that socket the client doesn't send any messages for the server to _read_, and the server doesn't _write_ any messages of its own to the client. 

> Is there support for multiple people?

The relay supports any number of pairwise (one-to-one) connections, and any number of document IDs. The document ID can stand for whatever you want it to — it might represent a team in a project-management app, or a channel in a chat app, or a literal document in a word processing app. So Alice, Bob, and Charlie might be collaborating on document `abc` (over three pairwise connections), while at the same time Charlie and Dwight are collaborating on document `xyz` (over a single pairwise connection).

**Comment by ryanhlewis** [comment]
{ type: 'Join', documentIds: ['abc'] }

Aha! Got it. They're two separate key pairs. 
Functionally, I send a JSON object that contains literally that information. 

```
Web socket string message:
{"type":"Introduction","userName":"bob","documentIds":["apples"]}
```

I got them finally talking to each other! Thanks.

I think I have an idea of what to do. Your information helped a lot!
I'll certainly let you know if I run into any more bugs, or find anything of interest in using your server.
